### ISSUE TITLE
english

### ISSUE THREAD

**Issue by susantha1995** [wanghaisheng/autovideo#2]
hi, GUI showing the Chinese language. is there any way to use it as English?

**Comment by wanghaisheng** [comment]
they are just for display purpose ,i dont think it will stop you  .take a picture and google translate can help
I am sure you can figure it out

**Comment by KishoreKaushal** [comment]
> 

The owner of this repo is a very chill guy. He doesn't care about the code quality and user-friendliness. Only care about the content and technology. Sigma programmer. I will take the pain of improving those stuff.

**Comment by wanghaisheng** [comment]
THANKS FOR YOUR input.
